[general]
# Configuraci贸n general de la aplicaci贸n
headless = false

[server]
# Configuraci贸n del servidor
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 100

[theme]
# Tema personalizado
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
# Configuraci贸n del navegador
gatherUsageStats = false
showErrorDetails = true
